### ISSUE TITLE
Testing & Fixture Data with Node-Neo4j

### ISSUE THREAD

**Issue by mtthgn** [thingdom/node-neo4j#158]
I was curious what the maintainer's approach to testing is when writing an application with a neo4j database. 

In my current implementation, I have a script that renames my `graph.db` in my neo4j files to something else (`graph.snapshot.db`, for example), and fills a _new_ `graph.db`  with fixture data via cypher queries. This feels like the wrong approach, but I haven't seen many approaches when digging around the internet.

I'd love to know the approach of the thingdom / fiftythree team!

**Comment by aseemk** [comment]
Hi @mtthgn! This is a good question with no single correct answer. =)

What we do at FiftyThree is to simply be robust to any possible existing data in the db (assuming it's all still valid as per our schema, so i.e. that it's all data generated by our code).

More specifically, our tests generate all their test data, and mainly rely on that. If your domain is a typical graph domain (e.g. a social network), this can work nicely since the test subgraphs are isolated.

E.g. our test suite for following on Mix looks like:

- Create three test users A, B, and C, with randomly generated email addresses.
- Test that initially, they have no followers, and they aren't following anyone.
- Have user A follow user B, and user B follow user C, etc. (or w/e).
- Etc.

With this approach, it doesn't matter at all what existing data there was in the graph, so we're also robust to multiple test runs, it's fast, etc.

In fact, this is also exactly what the test suite for the node-neo4j-template sample app looks like:

https://github.com/aseemk/node-neo4j-template/blob/master/test/models/user.js

Hope this helps!

**Comment by mtthgn** [comment]
Thanks for the insights, @aseemk!  Coming from sql-land, the thought of isolated graphs never occurred to me, but it greatly simplifies things!

**Comment by aseemk** [comment]
No problem, happy to help!

**Comment by ikwattro** [comment]
For simple setups like this, dropping and reinjecting content in the database in the setup and teardown steps does not really cause any problem.

However for large computation, benchmark tests, algorithm tests with relevant datasets, we use docker images.

when you pull the docker image it will be populated with the initial data, stopping and restarting the images takes far lot of less time than the previous process in order to have a fresh populated db at each step.

**Comment by aseemk** [comment]
Indeed! We do something similar at FiftyThree with AMIs (Amazon machine images), not so much for our automated tests, but for manual verification and visual testing. Our images are populated with a recent backup of our production data.
