### ISSUE TITLE
How do I get the created object? 

### ISSUE THREAD

**Issue by moshebeeri** [thingdom/node-neo4j#160]
```js
exports.createDirectory = function (req, res) {
  logger.info("exports moshe ");

  db.cypher({
    query: 'CREATE (n:Directory { name : {name} }) return n',
    params: {
      name: req.params.id,
    },
  }, function (err, results) {
    if (err) throw err;
    var result = results[0];
    if (!result) {
      console.log('No result.');
    } 
    return res.json(200, results);
  });

  return res.json(200, "createDirectory");
}
```

I just want to return the created object and the result object always empty, what am I doing wrong (I am a newbe to node js) 
Thanks,
Moshe.

**Comment by aseemk** [comment]
Remove the second (outer) `res.json`: you're returning the response right away there, before the database has had a chance to execute the query.

Your first (inner) `res.json` is fine. You should be seeing the results JSON there, not empty.

**Comment by underscoredam** [comment]
Just like @aseemk  said, the outer `res.json(200,"createDirectory")` is being called before the inner `res.json(200,results)`, this is because the inner `res.json` lies in a different function. You should remove the outer `res.json` so that the inner `res.json` is called as the data is fetched.

Final code will look like this. I hope it works.

    exports.createDirectory = function (req, res) {
      logger.info("exports moshe ");

      db.cypher({
        query: 'CREATE (n:Directory { name : {name} }) return n',
        params: {
          name: req.params.id,
        },
      }, function (err, results) {
        if (err) throw err;
        var result = results[0];
        if (!result) {
          console.log('No result.');
        } 
        return res.json(200, results);
      });
    }

By the way, `createDirectory` will not create a directory in the database immediately. It will take some time before time, because it happens asynchronously.

**Comment by aseemk** [comment]
Looks like this is answered. Thanks folks.
