### ISSUE TITLE
Whats current state of the project?

### ISSUE THREAD

**Issue by gyzerok** [thingdom/node-neo4j#168]
Is this project dead? Whats about version 2?

**Comment by aseemk** [comment]
Nope, very much alive! =)

Version 2 is fully implemented, and just in "release candidate" mode because I still have to write the final docs to tie everything together. Sorry that's taken me a while — I'm slow at writing to begin with, and it's been hard to find dedicated time lately with life things.

But, I made some good progress this weekend. Sneak peeks:

<img width="1092" alt="screenshot 2015-08-24 08 27 52" src="https://cloud.githubusercontent.com/assets/537838/9444235/4e2bf3ea-4a3a-11e5-8e67-a8264522bd5b.png">

<img width="1124" alt="screenshot 2015-08-24 08 29 16" src="https://cloud.githubusercontent.com/assets/537838/9444243/574e2d44-4a3a-11e5-8f3d-466b21576ff3.png">

I want to make the docs really good, because v2 is packed with a lot of goodness that isn't obvious. I also want to do my part to help make people write robust code from the start.

Hope that helps. Thanks for your patience. =)

**Comment by aseemk** [comment]
I'll move this over to your question on the v2 pull request: https://github.com/thingdom/node-neo4j/pull/145#issuecomment-134180523.
