### ISSUE TITLE
Impermanent / in-memory GraphDatabase

### ISSUE THREAD

**Issue by VanHumbeeckA** [thingdom/node-neo4j#185]
It would be awesome if node-neo4j also has the ability to create in-memory instances of neo4j (for testing purposes). This is already possible in Java (docs on the neo4j page itself), but there doesn't exist a decent solution for nodeJS at this point.

**Comment by aseemk** [comment]
Sorry for my delay in responding here, @VanHumbeeckA.

That would indeed be cool, but is unfortunately out of scope for this project. The biggest stumbling block by far would be that we'd need to implement a Cypher parser to handle Cypher queries that'd now modify this in-memory db, rather than simply sending those queries to Neo4j.

Feel free to re-open if you think of anything I'm missing!
