### ISSUE TITLE
loading with Webpack?

### ISSUE THREAD

**Issue by edanweis** [thingdom/node-neo4j#194]
I'm trying to load this using [angular2-webpack](https://github.com/preboot/angular2-webpack), but getting a bunch of errors, starting with: `Error: Cannot resolve module 'net' in ...`.  Could this be due to Webpack requiring commonjs?  Anyone tried this with Angular2?

**Comment by aseemk** [comment]
Sorry for the delay. I don't have any experience here. Try posting on Stack Overflow, or ask the Google Group or Slack?

https://github.com/thingdom/node-neo4j/tree/v2#help

I'll go ahead close this assuming it's not an issue with node-neo4j (since this lib isn't doing anything special for browsers), but feel free to re-open if there's something that can be done here. Thanks!
